#!/bin/bash

sudo pacman -S neovim unzip python python-pip --confirm

curl https://get.volta.sh | bash
volta install node
volta install yarn 
volta install pnpm 

curl -fsSL https://deno.land/install.sh | bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y --profile complete

curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh | bash -s -- -y 
